/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EurasiaRouteImport } from './routes/eurasia'
import { Route as IndexRouteImport } from './routes/index'

const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EurasiaRoute = EurasiaRouteImport.update({
  id: '/eurasia',
  path: '/eurasia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eurasia' | '/news' | '/policy' | '/rates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eurasia' | '/news' | '/policy' | '/rates'
  id: '__root__' | '/' | '/eurasia' | '/news' | '/policy' | '/rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EurasiaRoute: typeof EurasiaRoute
  NewsRoute: typeof NewsRoute
  PolicyRoute: typeof PolicyRoute
  RatesRoute: typeof RatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eurasia': {
      id: '/eurasia'
      path: '/eurasia'
      fullPath: '/eurasia'
      preLoaderRoute: typeof EurasiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EurasiaRoute: EurasiaRoute,
  NewsRoute: NewsRoute,
  PolicyRoute: PolicyRoute,
  RatesRoute: RatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
