/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EurasiaRouteImport } from './routes/eurasia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EurasiaRoute = EurasiaRouteImport.update({
  id: '/eurasia',
  path: '/eurasia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/admin/routes',
  path: '/admin/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/industries': typeof IndustriesRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/industries': typeof IndustriesRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eurasia': typeof EurasiaRoute
  '/industries': typeof IndustriesRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/rates': typeof RatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eurasia'
    | '/industries'
    | '/news'
    | '/policy'
    | '/rates'
    | '/admin/login'
    | '/admin/routes'
    | '/article/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eurasia'
    | '/industries'
    | '/news'
    | '/policy'
    | '/rates'
    | '/admin/login'
    | '/admin/routes'
    | '/article/$id'
  id:
    | '__root__'
    | '/'
    | '/eurasia'
    | '/industries'
    | '/news'
    | '/policy'
    | '/rates'
    | '/admin/login'
    | '/admin/routes'
    | '/article/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EurasiaRoute: typeof EurasiaRoute
  IndustriesRoute: typeof IndustriesRoute
  NewsRoute: typeof NewsRoute
  PolicyRoute: typeof PolicyRoute
  RatesRoute: typeof RatesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  ArticleIdRoute: typeof ArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eurasia': {
      id: '/eurasia'
      path: '/eurasia'
      fullPath: '/eurasia'
      preLoaderRoute: typeof EurasiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EurasiaRoute: EurasiaRoute,
  IndustriesRoute: IndustriesRoute,
  NewsRoute: NewsRoute,
  PolicyRoute: PolicyRoute,
  RatesRoute: RatesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  ArticleIdRoute: ArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
