create table if not exists public.eu_customs_measures (
 id bigint generated by default as identity primary key,
 cn_code text not null check (cn_code ~ '^[0-9]{4,10}$'),
 origin_country text,
 destination_country text,
 measure_type text not null check (measure_type in ('THIRD_COUNTRY_DUTY','PREFERENCE','VAT','REQUIREMENT','REGULATION')),
 rate_percent numeric, rate_text text, title text not null, detail text, legal_basis text, source_url text not null,
 valid_from date, valid_to date, is_active boolean not null default true, metadata jsonb not null default '{}'::jsonb,
 ingested_at timestamptz not null default now()
);
create index if not exists eu_customs_measures_lookup_idx on public.eu_customs_measures(cn_code,origin_country,destination_country,measure_type,is_active);
alter table public.eu_customs_measures enable row level security;
grant select on public.eu_customs_measures to anon, authenticated;
create policy "eu customs measures public read" on public.eu_customs_measures for select to anon,authenticated using (is_active=true);