-- Official customs nomenclature cache.
-- Source rows must be traceable to a named official publication and validity period.
create table if not exists public.customs_nomenclature (
  id bigint generated by default as identity primary key,
  market text not null check (market in ('EU')),
  nomenclature text not null check (nomenclature in ('HS','CN','TARIC')),
  code text not null,
  parent_code text,
  description text not null,
  level smallint not null check (level in (2,4,6,8,10)),
  valid_from date not null,
  valid_to date,
  source_name text not null,
  source_url text not null,
  source_version text not null,
  source_retrieved_at timestamptz not null default now(),
  is_active boolean not null default true,
  search_document tsvector generated always as (
    to_tsvector('simple', coalesce(code,'') || ' ' || coalesce(description,''))
  ) stored,
  unique (market, nomenclature, code, valid_from)
);

create index if not exists customs_nomenclature_code_idx
  on public.customs_nomenclature (market, nomenclature, code);

create index if not exists customs_nomenclature_parent_idx
  on public.customs_nomenclature (market, nomenclature, parent_code);

create index if not exists customs_nomenclature_search_idx
  on public.customs_nomenclature using gin (search_document);

comment on table public.customs_nomenclature is
  'Versioned official customs nomenclature. Never populate with LLM-generated codes or descriptions.';
