create table if not exists public.customs_classification_evidence (
  id bigint generated by default as identity primary key,
  market text not null check (market in ('EU')),
  cn_code text not null check (cn_code ~ '^[0-9]{4,10}$'),
  source_type text not null check (source_type in ('CLASS','EBTI','CN_EXPLANATORY_NOTE','CLASSIFICATION_REGULATION','CCC_CONCLUSION','CJEU')),
  source_id text,
  title text not null,
  product_description text,
  decision_summary text,
  legal_basis text,
  decision_date date,
  valid_from date,
  valid_to date,
  source_url text not null,
  source_version text,
  source_hash text,
  is_active boolean not null default true,
  ingested_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (source_type, source_id)
);
create index if not exists customs_classification_evidence_cn_code_idx on public.customs_classification_evidence (cn_code);
create index if not exists customs_classification_evidence_source_type_idx on public.customs_classification_evidence (source_type);
alter table public.customs_classification_evidence enable row level security;
grant select on public.customs_classification_evidence to anon, authenticated;
create policy "classification evidence is publicly readable"
on public.customs_classification_evidence for select to anon, authenticated using (is_active = true);
