// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmgbvqczmyjixkqbruzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZ2J2cWN6bXlqaXhrcWJydXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MTIyNzIsImV4cCI6MjA5NTA4ODI3Mn0.cvMs8vhretzH7vL6w-UN8XkWJoOpXpQvLs_HIOTTG0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});